graphhopper:
  datareader.file: maps/india_nepal.osm.pbf
  graph.location: graph-cache

  graph.encoded_values: car_access,car_average_speed,road_access

  import.osm.ignored_highways:
    - footway
    - path
    - steps
    - cycleway
    - bridleway
    - corridor
    - construction

  profiles:
    - name: car
      weighting: custom
      custom_model:
        speed:
          - if: "true"
            limit_to: car_average_speed
        priority:
          - if: "road_access == DESTINATION"
            multiply_by: 0

server:
  application_connectors:
    - type: http
      port: 8989